name: Push and Pull Notifier

on:
  push:
    branches: [main]  # or master if you're using that
  pull_request:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say pushed or pulled
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "Code was pushed to the repository."
          else
            echo "A pull request was created or updated."
          fi
